/**
 * SprintScale CMS — In-App Help & Training Manifest
 * Canonical metadata registry for all 34 allowlisted user guides and 52 micro-videos.
 */

import { HelpCategoryDefinition, HelpGuideMetadata, HelpVideoMetadata } from './types';

export const HELP_CATEGORIES: HelpCategoryDefinition[] = [
  {
    id: 'getting-started',
    name: 'Getting Started & Role Guides',
    description: 'Onboarding workflows, initial setup, and role-specific guides for staff and parents.',
    iconName: 'Compass',
    order: 1,
  },
  {
    id: 'core-operations',
    name: 'Core Operations',
    description: 'Daily attendance, roll call, student directory, parent records, and booking scheduling.',
    iconName: 'CalendarCheck',
    order: 2,
  },
  {
    id: 'safeguarding',
    name: 'Safeguarding & Incidents',
    description: 'First aid incident logging, body mapping, emergency contacts, and safeguarding protocols.',
    iconName: 'ShieldAlert',
    order: 3,
  },
  {
    id: 'finance',
    name: 'Finance, Billing & Payments',
    description: 'Invoicing, agreed-fee plans, payment reconciliation, and childcare voucher processing.',
    iconName: 'Wallet',
    order: 4,
  },
  {
    id: 'administration',
    name: 'Administration & System Setup',
    description: 'Multi-centre configuration, staff access permissions, academic year roll, and settings.',
    iconName: 'Settings',
    order: 5,
  },
  {
    id: 'troubleshooting',
    name: 'Troubleshooting & Support',
    description: 'Common edge cases, resolution runbooks, and recovery workflows across all modules.',
    iconName: 'LifeBuoy',
    order: 6,
  },
  {
    id: 'master-manual',
    name: 'Master User Manual',
    description: 'Continuous 5-part end-to-end operational journey through the entire CMS lifecycle.',
    iconName: 'BookOpen',
    order: 7,
  },
];

export const HELP_GUIDES: HelpGuideMetadata[] = [
  // 1. Getting Started
  {
    id: 'qs-owner',
    slug: 'owner-first-30-minutes',
    title: 'Organisation Owner: First 30 Minutes',
    description: 'Essential orientation for club founders and owners setting up venues, staff, and billing.',
    category: 'getting-started',
    audience: 'Organisation Owners',
    targetAudience: ["ORG_OWNER"],
    recommendedStaffRoles: ["ORG_OWNER"],
    contentPath: 'getting-started/owner-first-30-minutes.md',
    order: 1,
    readingTimeMinutes: 5,
    keywords: ['owner', 'setup', 'onboarding', 'venues', 'first 30 minutes'],
    screenshots: ['SS-D6-S001', 'SS-D6-S037', 'SS-D6-S040', 'SS-D6-S026'],
    videos: ['SS-D6-V022', 'SS-D6-V023'],
  },
  {
    id: 'qs-manager',
    slug: 'manager-first-30-minutes',
    title: 'Centre Manager: First 30 Minutes',
    description: 'Quick-start guide for centre managers supervising daily registrations, registers, and staff.',
    category: 'getting-started',
    audience: 'Centre Managers',
    targetAudience: ["MANAGER","ORG_OWNER"],
    recommendedStaffRoles: ["MANAGER","ORG_OWNER"],
    contentPath: 'getting-started/manager-first-30-minutes.md',
    order: 2,
    readingTimeMinutes: 5,
    keywords: ['manager', 'quickstart', 'daily register', 'registrations', 'centre'],
    screenshots: ['SS-D6-S001', 'SS-D6-S014', 'SS-D6-S009', 'SS-D6-S011'],
    videos: ['SS-D6-V002', 'SS-D6-V006'],
  },
  {
    id: 'qs-tutor',
    slug: 'tutor-first-day',
    title: 'Tutor / Club Leader: First Day Guide',
    description: 'Session roll call, medical badge recognition, incident logging, and kiosk operation.',
    category: 'getting-started',
    audience: 'Tutors and Activity Leaders',
    targetAudience: ["TUTOR"],
    recommendedStaffRoles: ["TUTOR"],
    contentPath: 'getting-started/tutor-first-day.md',
    order: 3,
    readingTimeMinutes: 4,
    keywords: ['tutor', 'club leader', 'attendance', 'allergies', 'first day', 'kiosk'],
    screenshots: ['SS-D6-S014', 'SS-D6-S015', 'SS-D6-S006', 'SS-D6-S023'],
    videos: ['SS-D6-V006', 'SS-D6-V007', 'SS-D6-V012'],
  },
  {
    id: 'qs-parent',
    slug: 'parent-getting-started',
    title: 'Parent Portal: Getting Started',
    description: 'Overview of parent self-service for registration, session bookings, and invoice review.',
    category: 'getting-started',
    audience: 'Parents & Staff Reference',
    targetAudience: ["PARENT","FRONT_DESK","MANAGER"],
    recommendedStaffRoles: ["FRONT_DESK","MANAGER"],
    contentPath: 'getting-started/parent-getting-started.md',
    order: 4,
    readingTimeMinutes: 4,
    keywords: ['parent', 'portal', 'login', 'magic link', 'booking'],
    screenshots: ['SS-D6-S047', 'SS-D6-S048', 'SS-D6-S050'],
    videos: ['SS-D6-V001', 'SS-D6-V005'],
  },
  {
    id: 'rg-owner',
    slug: 'owner-guide',
    title: 'Role Guide: Organisation Owner',
    description: 'Comprehensive operational responsibility guide for organisation owners.',
    category: 'getting-started',
    audience: 'Organisation Owners',
    targetAudience: ["ORG_OWNER"],
    recommendedStaffRoles: ["ORG_OWNER"],
    contentPath: 'getting-started/owner-guide.md',
    order: 5,
    readingTimeMinutes: 10,
    keywords: ['owner guide', 'compliance', 'governance', 'multi-centre', 'finance'],
    screenshots: ['SS-D6-S026', 'SS-D6-S039', 'SS-D6-S041', 'SS-D6-S046'],
    videos: ['SS-D6-V016', 'SS-D6-V022', 'SS-D6-V024'],
  },
  {
    id: 'rg-manager',
    slug: 'manager-guide',
    title: 'Role Guide: Centre Manager',
    description: 'Detailed handbook covering centre workflows, parent triage, and daily reporting.',
    category: 'getting-started',
    audience: 'Centre Managers',
    targetAudience: ["MANAGER","ORG_OWNER"],
    recommendedStaffRoles: ["MANAGER","ORG_OWNER"],
    contentPath: 'getting-started/manager-guide.md',
    order: 6,
    readingTimeMinutes: 9,
    keywords: ['manager guide', 'operations', 'session control', 'triage', 'centre oversight'],
    screenshots: ['SS-D6-S009', 'SS-D6-S010', 'SS-D6-S011', 'SS-D6-S020'],
    videos: ['SS-D6-V002', 'SS-D6-V004', 'SS-D6-V010'],
  },
  {
    id: 'rg-front-desk',
    slug: 'front-desk-guide',
    title: 'Role Guide: Front Desk Operations',
    description: 'Front-of-house parent interactions, arrival check-in, and registration intake.',
    category: 'getting-started',
    audience: 'Front Desk Staff',
    targetAudience: ["FRONT_DESK","MANAGER","ORG_OWNER"],
    recommendedStaffRoles: ["FRONT_DESK","MANAGER","ORG_OWNER"],
    contentPath: 'getting-started/front-desk-guide.md',
    order: 7,
    readingTimeMinutes: 8,
    keywords: ['front desk', 'check in', 'pick up', 'parent reception', 'kiosk'],
    screenshots: ['SS-D6-S018', 'SS-D6-S019', 'SS-D6-S003', 'SS-D6-S012'],
    videos: ['SS-D6-V003', 'SS-D6-V007', 'SS-D6-V008'],
  },
  {
    id: 'rg-tutor',
    slug: 'tutor-guide',
    title: 'Role Guide: Tutor & Session Delivery',
    description: 'Classroom roll call, student medical badges, behaviour notes, and safety protocols.',
    category: 'getting-started',
    audience: 'Tutors and Activity Leaders',
    targetAudience: ["TUTOR"],
    recommendedStaffRoles: ["TUTOR"],
    contentPath: 'getting-started/tutor-guide.md',
    order: 8,
    readingTimeMinutes: 8,
    keywords: ['tutor guide', 'roll call', 'classroom', 'medical notes', 'incident protocol'],
    screenshots: ['SS-D6-S014', 'SS-D6-S015', 'SS-D6-S006', 'SS-D6-S022'],
    videos: ['SS-D6-V006', 'SS-D6-V011', 'SS-D6-V012'],
  },
  {
    id: 'rg-parent',
    slug: 'parent-portal-guide',
    title: 'Parent Portal: Complete User Guide',
    description: 'Step-by-step parent manual for managing children, bookings, and payments.',
    category: 'getting-started',
    audience: 'Parents & Front Desk Staff',
    targetAudience: ["PARENT","FRONT_DESK","MANAGER"],
    recommendedStaffRoles: ["FRONT_DESK","MANAGER"],
    contentPath: 'getting-started/parent-portal-guide.md',
    order: 9,
    readingTimeMinutes: 7,
    keywords: ['parent portal', 'online bookings', 'childcare vouchers', 'invoices'],
    screenshots: ['SS-D6-S047', 'SS-D6-S048', 'SS-D6-S049', 'SS-D6-S050'],
    videos: ['SS-D6-V001', 'SS-D6-V005', 'SS-D6-V031'],
  },

  // 2. Core Operations
  {
    id: 'fm-attendance',
    slug: 'attendance-roll-call',
    title: 'Functional Manual: Attendance & Roll Call',
    description: 'Live attendance registers, check-in/out timestamps, absence overrides, and kiosk mode.',
    category: 'core-operations',
    audience: 'Tutors, Managers, Front Desk',
    targetAudience: ["TUTOR","MANAGER","FRONT_DESK","ORG_OWNER"],
    recommendedStaffRoles: ["TUTOR","MANAGER","FRONT_DESK","ORG_OWNER"],
    contentPath: 'core-operations/attendance-roll-call.md',
    order: 10,
    readingTimeMinutes: 12,
    keywords: ['attendance', 'register', 'roll call', 'check in', 'check out', 'absence', 'kiosk'],
    screenshots: ['SS-D6-S014', 'SS-D6-S015', 'SS-D6-S016', 'SS-D6-S017', 'SS-D6-S018', 'SS-D6-S019'],
    videos: ['SS-D6-V006', 'SS-D6-V007', 'SS-D6-V008', 'SS-D6-V009'],
  },
  {
    id: 'fm-bookings',
    slug: 'bookings-scheduling',
    title: 'Functional Manual: Bookings & Scheduling',
    description: 'Session scheduling, ad-hoc single bookings, term booking plans, and capacity limits.',
    category: 'core-operations',
    audience: 'Managers, Front Desk, Owners',
    targetAudience: ["MANAGER","FRONT_DESK","ORG_OWNER"],
    recommendedStaffRoles: ["MANAGER","FRONT_DESK","ORG_OWNER"],
    contentPath: 'core-operations/bookings-scheduling.md',
    order: 11,
    readingTimeMinutes: 10,
    keywords: ['bookings', 'schedule', 'sessions', 'recurring plan', 'capacity', 'reschedule'],
    screenshots: ['SS-D6-S011', 'SS-D6-S012', 'SS-D6-S013', 'SS-D6-S069', 'SS-D6-S070'],
    videos: ['SS-D6-V003', 'SS-D6-V004', 'SS-D6-V039', 'SS-D6-V040'],
  },
  {
    id: 'fm-students',
    slug: 'children-students',
    title: 'Functional Manual: Children & Students Directory',
    description: 'Student profiles, allergy/medical flags, emergency contacts, and class allocations.',
    category: 'core-operations',
    audience: 'All Staff Roles',
    targetAudience: ["MANAGER","FRONT_DESK","TUTOR","ORG_OWNER"],
    recommendedStaffRoles: ["MANAGER","FRONT_DESK","TUTOR","ORG_OWNER"],
    contentPath: 'core-operations/children-students.md',
    order: 12,
    readingTimeMinutes: 10,
    keywords: ['students', 'children', 'allergies', 'dietary', 'medical', 'contacts', 'profile'],
    screenshots: ['SS-D6-S005', 'SS-D6-S006', 'SS-D6-S066'],
    videos: ['SS-D6-V033', 'SS-D6-V035', 'SS-D6-V050'],
  },
  {
    id: 'fm-student-records',
    slug: 'student-records-notes',
    title: 'Functional Manual: Student Records, Medical & Session Notes',
    description: 'Session observations, medical notes, academic scorecards, and behavioural tracking.',
    category: 'core-operations',
    audience: 'Tutors, Managers, Front Desk',
    targetAudience: ["TUTOR","MANAGER","FRONT_DESK","ORG_OWNER"],
    recommendedStaffRoles: ["TUTOR","MANAGER","FRONT_DESK","ORG_OWNER"],
    contentPath: 'core-operations/student-records-notes.md',
    order: 13,
    readingTimeMinutes: 8,
    keywords: ['student notes', 'medical notes', 'observations', 'records', 'progress'],
    screenshots: ['SS-D6-S022', 'SS-D6-S066'],
    videos: ['SS-D6-V011', 'SS-D6-V050'],
  },
  {
    id: 'fm-parents',
    slug: 'parents-family-records',
    title: 'Functional Manual: Parents & Family Records',
    description: 'Parent accounts, sibling linkages, authorised collectors, and family recovery bin.',
    category: 'core-operations',
    audience: 'Managers, Front Desk, Owners',
    targetAudience: ["MANAGER","FRONT_DESK","ORG_OWNER"],
    recommendedStaffRoles: ["MANAGER","FRONT_DESK","ORG_OWNER"],
    contentPath: 'core-operations/parents-family-records.md',
    order: 14,
    readingTimeMinutes: 10,
    keywords: ['parents', 'family', 'collectors', 'recovery bin', 'soft delete', 'restore'],
    screenshots: ['SS-D6-S002', 'SS-D6-S003', 'SS-D6-S004', 'SS-D6-S045', 'SS-D6-S065'],
    videos: ['SS-D6-V025', 'SS-D6-V026', 'SS-D6-V034'],
  },
  {
    id: 'fm-registrations',
    slug: 'registrations-intake',
    title: 'Functional Manual: Registrations & Intake Review',
    description: 'Processing parent registrations, child record matching, approvals, and decline audit logs.',
    category: 'core-operations',
    audience: 'Managers, Front Desk, Owners',
    targetAudience: ["MANAGER","FRONT_DESK","ORG_OWNER"],
    recommendedStaffRoles: ["MANAGER","FRONT_DESK","ORG_OWNER"],
    contentPath: 'core-operations/registrations-intake.md',
    order: 15,
    readingTimeMinutes: 10,
    keywords: ['registrations', 'intake', 'triage', 'approval', 'signatures', 'onboarding'],
    screenshots: ['SS-D6-S007', 'SS-D6-S008', 'SS-D6-S009', 'SS-D6-S010', 'SS-D6-S072'],
    videos: ['SS-D6-V001', 'SS-D6-V002', 'SS-D6-V036', 'SS-D6-V037'],
  },
  {
    id: 'fm-communications',
    slug: 'communications-notifications',
    title: 'Functional Manual: Communications & Notification Dispatches',
    description: 'Email broadcasts, parent notices, delivery metrics, and communication consent.',
    category: 'core-operations',
    audience: 'Managers, Owners',
    targetAudience: ["MANAGER","ORG_OWNER"],
    recommendedStaffRoles: ["MANAGER","ORG_OWNER"],
    contentPath: 'core-operations/communications-notifications.md',
    order: 16,
    readingTimeMinutes: 8,
    keywords: ['communications', 'broadcast', 'notifications', 'email', 'announcements'],
    screenshots: ['SS-D6-S044', 'SS-D6-S053', 'SS-D6-S059'],
    videos: ['SS-D6-V027', 'SS-D6-V048'],
  },

  // 3. Safeguarding & Incidents
  {
    id: 'fm-incidents',
    slug: 'incidents-safeguarding',
    title: 'Functional Manual: Incidents & Safeguarding Protocol',
    description: 'Accident logging, body maps, first aid records, and restricted safeguarding notes.',
    category: 'safeguarding',
    audience: 'All Staff Roles',
    targetAudience: ["MANAGER","FRONT_DESK","TUTOR","ORG_OWNER"],
    recommendedStaffRoles: ["MANAGER","FRONT_DESK","TUTOR","ORG_OWNER"],
    contentPath: 'safeguarding/incidents-safeguarding.md',
    order: 17,
    readingTimeMinutes: 11,
    keywords: ['incidents', 'safeguarding', 'first aid', 'accident', 'body map', 'confidential'],
    screenshots: ['SS-D6-S023', 'SS-D6-S024', 'SS-D6-S025'],
    videos: ['SS-D6-V012', 'SS-D6-V013', 'SS-D6-V014'],
  },

  // 4. Finance & Payments
  {
    id: 'fm-finance-overview',
    slug: 'finance-overview',
    title: 'Functional Manual: Finance Overview & KPIs',
    description: 'Executive revenue summaries, outstanding balances, and financial exports.',
    category: 'finance',
    audience: 'Organisation Owners, Senior Managers',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'finance/finance-overview.md',
    order: 18,
    readingTimeMinutes: 9,
    keywords: ['finance', 'revenue', 'kpis', 'outstanding', 'csv export', 'balance'],
    screenshots: ['SS-D6-S026', 'SS-D6-S076'],
    videos: ['SS-D6-V015', 'SS-D6-V041'],
  },
  {
    id: 'fm-invoices',
    slug: 'invoices-billing',
    title: 'Functional Manual: Invoices & Billing Management',
    description: 'Batch invoice generation, itemized charges, invoice editing, and voiding controls.',
    category: 'finance',
    audience: 'Organisation Owners, Finance Staff',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'finance/invoices-billing.md',
    order: 19,
    readingTimeMinutes: 11,
    keywords: ['invoices', 'billing', 'batch run', 'void', 'pdf', 'receipt'],
    screenshots: ['SS-D6-S029', 'SS-D6-S030', 'SS-D6-S031', 'SS-D6-S036', 'SS-D6-S062'],
    videos: ['SS-D6-V016', 'SS-D6-V017', 'SS-D6-V042', 'SS-D6-V044'],
  },
  {
    id: 'fm-payments',
    slug: 'payments-reconciliation',
    title: 'Functional Manual: Payments & Reconciliation',
    description: 'Offline cash/bank payments, childcare voucher (TFC) allocation, and partial payments.',
    category: 'finance',
    audience: 'Organisation Owners, Finance Staff',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'finance/payments-reconciliation.md',
    order: 20,
    readingTimeMinutes: 11,
    keywords: ['payments', 'reconciliation', 'cash', 'bank transfer', 'childcare vouchers', 'tfc'],
    screenshots: ['SS-D6-S032', 'SS-D6-S033', 'SS-D6-S034', 'SS-D6-S035', 'SS-D6-S064'],
    videos: ['SS-D6-V018', 'SS-D6-V019', 'SS-D6-V020', 'SS-D6-V043'],
  },
  {
    id: 'fm-agreed-fees',
    slug: 'agreed-fee-billing',
    title: 'Functional Manual: Agreed-Fee Family Billing Plans',
    description: 'Recurring monthly fixed fees, sibling discount coverage, and effective date management.',
    category: 'finance',
    audience: 'Organisation Owners, Finance Staff',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'finance/agreed-fee-billing.md',
    order: 21,
    readingTimeMinutes: 9,
    keywords: ['agreed fee', 'monthly fee', 'sibling coverage', 'billing plan', 'discounts'],
    screenshots: ['SS-D6-S027', 'SS-D6-S028'],
    videos: ['SS-D6-V021', 'SS-D6-V045'],
  },

  // 5. Administration & Settings
  {
    id: 'fm-centres',
    slug: 'centres-multi-centre',
    title: 'Functional Manual: Multi-Centre Administration',
    description: 'Managing venues, room capacities, operating times, and centre-specific banking details.',
    category: 'administration',
    audience: 'Organisation Owners, Managers',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'administration/centres-multi-centre.md',
    order: 22,
    readingTimeMinutes: 9,
    keywords: ['centres', 'venues', 'multi-centre', 'capacity', 'operating hours', 'bank details'],
    screenshots: ['SS-D6-S037', 'SS-D6-S038', 'SS-D6-S039', 'SS-D6-S056', 'SS-D6-S057'],
    videos: ['SS-D6-V022', 'SS-D6-V046'],
  },
  {
    id: 'fm-staff-permissions',
    slug: 'staff-access-permissions',
    title: 'Functional Manual: Staff Directory & Access Permissions',
    description: 'Inviting staff, role assignment, multi-centre membership, and deactivation safeguards.',
    category: 'administration',
    audience: 'Organisation Owners, Managers',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'administration/staff-access-permissions.md',
    order: 23,
    readingTimeMinutes: 10,
    keywords: ['staff', 'team', 'invites', 'permissions', 'roles', 'deactivation'],
    screenshots: ['SS-D6-S040', 'SS-D6-S041', 'SS-D6-S042', 'SS-D6-S043', 'SS-D6-S052', 'SS-D6-S058'],
    videos: ['SS-D6-V023', 'SS-D6-V024', 'SS-D6-V047'],
  },
  {
    id: 'fm-academic-year',
    slug: 'academic-year-data-maintenance',
    title: 'Functional Manual: Academic-Year Rollover & Maintenance',
    description: 'End-of-year rollover procedures, cohort promotion, and annual archive hygiene.',
    category: 'administration',
    audience: 'Organisation Owners',
    targetAudience: ["ORG_OWNER"],
    recommendedStaffRoles: ["ORG_OWNER"],
    contentPath: 'administration/academic-year-data-maintenance.md',
    order: 24,
    readingTimeMinutes: 8,
    keywords: ['academic year', 'rollover', 'cohorts', 'data maintenance', 'archive'],
    screenshots: ['SS-D6-S005', 'SS-D6-S037'],
    videos: ['SS-D6-V022', 'SS-D6-V033'],
  },
  {
    id: 'fm-administration-settings',
    slug: 'administration-settings',
    title: 'Functional Manual: Organisation & Centre Settings',
    description: 'Organisation metadata, contact information, branding, and integration statuses.',
    category: 'administration',
    audience: 'Organisation Owners',
    targetAudience: ["ORG_OWNER"],
    recommendedStaffRoles: ["ORG_OWNER"],
    contentPath: 'administration/administration-settings.md',
    order: 25,
    readingTimeMinutes: 7,
    keywords: ['settings', 'organisation profile', 'branding', 'wonde', 'integrations'],
    screenshots: ['SS-D6-S054', 'SS-D6-S055', 'SS-D6-S078'],
    videos: ['SS-D6-V032', 'SS-D6-V049'],
  },

  // 6. Troubleshooting Handbooks
  {
    id: 'tb-family-booking',
    slug: 'family-booking-troubleshooting',
    title: 'Troubleshooting: Family & Booking Workflows',
    description: 'Resolution guides for duplicate parents, booking clash alerts, and intake edge cases.',
    category: 'troubleshooting',
    audience: 'Managers, Front Desk, Owners',
    targetAudience: ["MANAGER","FRONT_DESK","ORG_OWNER"],
    recommendedStaffRoles: ["MANAGER","FRONT_DESK","ORG_OWNER"],
    contentPath: 'troubleshooting/family-booking-troubleshooting.md',
    order: 26,
    readingTimeMinutes: 9,
    keywords: ['troubleshooting', 'booking error', 'duplicate parent', 'clash', 'reschedule'],
    screenshots: ['SS-D6-S012', 'SS-D6-S070', 'SS-D6-S071'],
    videos: ['SS-D6-V038', 'SS-D6-V039', 'SS-D6-V040'],
  },
  {
    id: 'tb-attendance-safeguarding',
    slug: 'attendance-safeguarding-troubleshooting',
    title: 'Troubleshooting: Attendance & Safeguarding Operations',
    description: 'Handling missing register children, PIN kiosk lockouts, and emergency incident edits.',
    category: 'troubleshooting',
    audience: 'Tutors, Managers, Front Desk',
    targetAudience: ["TUTOR","MANAGER","FRONT_DESK","ORG_OWNER"],
    recommendedStaffRoles: ["TUTOR","MANAGER","FRONT_DESK","ORG_OWNER"],
    contentPath: 'troubleshooting/attendance-safeguarding-troubleshooting.md',
    order: 27,
    readingTimeMinutes: 9,
    keywords: ['troubleshooting', 'attendance error', 'missing child', 'kiosk locked', 'incident record'],
    screenshots: ['SS-D6-S017', 'SS-D6-S020', 'SS-D6-S021', 'SS-D6-S067'],
    videos: ['SS-D6-V009', 'SS-D6-V010'],
  },
  {
    id: 'tb-finance',
    slug: 'finance-troubleshooting',
    title: 'Troubleshooting: Invoices, Billing & Payments',
    description: 'Resolving unallocated childcare vouchers, overpayment handling, and invoice voiding.',
    category: 'troubleshooting',
    audience: 'Organisation Owners, Finance Staff',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'troubleshooting/finance-troubleshooting.md',
    order: 28,
    readingTimeMinutes: 8,
    keywords: ['troubleshooting', 'invoice discrepancy', 'voucher mismatch', 'unallocated payment'],
    screenshots: ['SS-D6-S034', 'SS-D6-S035', 'SS-D6-S062'],
    videos: ['SS-D6-V043', 'SS-D6-V044', 'SS-D6-V045'],
  },
  {
    id: 'tb-administration',
    slug: 'administration-troubleshooting',
    title: 'Troubleshooting: Multi-Centre & Team Administration',
    description: 'Diagnosing zero-centre staff locks, expired staff invitations, and role elevation.',
    category: 'troubleshooting',
    audience: 'Organisation Owners, Managers',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'troubleshooting/administration-troubleshooting.md',
    order: 29,
    readingTimeMinutes: 8,
    keywords: ['troubleshooting', 'staff lockout', 'expired invite', 'zero centre', 'permissions error'],
    screenshots: ['SS-D6-S043', 'SS-D6-S058', 'SS-D6-S074'],
    videos: ['SS-D6-V046', 'SS-D6-V047', 'SS-D6-V052'],
  },

  // 7. Master User Manual
  {
    id: 'mm-01-foundations',
    slug: 'master-system-foundations',
    title: 'Master User Manual: 01 System Foundations & Architecture',
    description: 'Core platform principles, navigation landmarks, theme toggles, and tenant boundaries.',
    category: 'master-manual',
    audience: 'All Staff Roles',
    targetAudience: ["ORG_OWNER","MANAGER","FRONT_DESK","TUTOR"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER","FRONT_DESK","TUTOR"],
    contentPath: 'master-manual/01-system-foundations.md',
    order: 30,
    readingTimeMinutes: 14,
    keywords: ['master manual', 'architecture', 'foundations', 'design system', 'tenancy'],
    screenshots: ['SS-D6-S001', 'SS-D6-S053'],
    videos: ['SS-D6-V022', 'SS-D6-V032'],
  },
  {
    id: 'mm-02-family-booking',
    slug: 'master-family-to-booking',
    title: 'Master User Manual: 02 Family to Booking Journey',
    description: 'End-to-end journey from initial parent registration through booking confirmation.',
    category: 'master-manual',
    audience: 'Managers, Front Desk, Owners',
    targetAudience: ["ORG_OWNER","MANAGER","FRONT_DESK"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER","FRONT_DESK"],
    contentPath: 'master-manual/02-family-to-booking-journey.md',
    order: 31,
    readingTimeMinutes: 11,
    keywords: ['master manual', 'family journey', 'intake', 'booking flow', 'registration lifecycle'],
    screenshots: ['SS-D6-S007', 'SS-D6-S009', 'SS-D6-S011', 'SS-D6-S013'],
    videos: ['SS-D6-V001', 'SS-D6-V002', 'SS-D6-V003', 'SS-D6-V004'],
  },
  {
    id: 'mm-03-attendance-safeguarding',
    slug: 'master-attendance-to-safeguarding',
    title: 'Master User Manual: 03 Attendance to Safeguarding Journey',
    description: 'Complete daily operational session lifecycle: register, arrivals, notes, and incidents.',
    category: 'master-manual',
    audience: 'Tutors, Managers, Front Desk',
    targetAudience: ["ORG_OWNER","MANAGER","FRONT_DESK","TUTOR"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER","FRONT_DESK","TUTOR"],
    contentPath: 'master-manual/03-attendance-to-safeguarding-journey.md',
    order: 32,
    readingTimeMinutes: 11,
    keywords: ['master manual', 'daily operations', 'session lifecycle', 'first aid', 'safeguarding audit'],
    screenshots: ['SS-D6-S014', 'SS-D6-S015', 'SS-D6-S022', 'SS-D6-S023'],
    videos: ['SS-D6-V006', 'SS-D6-V007', 'SS-D6-V011', 'SS-D6-V012'],
  },
  {
    id: 'mm-04-finance-billing',
    slug: 'master-finance-billing-payments',
    title: 'Master User Manual: 04 Finance, Billing & Payments Journey',
    description: 'Comprehensive financial cycle from agreed fees to batch invoicing and voucher reconciliation.',
    category: 'master-manual',
    audience: 'Organisation Owners, Finance Staff',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'master-manual/04-finance-billing-payments-journey.md',
    order: 33,
    readingTimeMinutes: 12,
    keywords: ['master manual', 'financial lifecycle', 'invoicing run', 'payment allocation', 'vouchers'],
    screenshots: ['SS-D6-S026', 'SS-D6-S027', 'SS-D6-S029', 'SS-D6-S034'],
    videos: ['SS-D6-V015', 'SS-D6-V016', 'SS-D6-V018', 'SS-D6-V020'],
  },
  {
    id: 'mm-05-administration-operations',
    slug: 'master-administration-operations',
    title: 'Master User Manual: 05 Administration & Operations',
    description: 'Master governance, venue setup, role hierarchies, notifications, and security standards.',
    category: 'master-manual',
    audience: 'Organisation Owners, Managers',
    targetAudience: ["ORG_OWNER","MANAGER"],
    recommendedStaffRoles: ["ORG_OWNER","MANAGER"],
    contentPath: 'master-manual/05-administration-and-operations.md',
    order: 34,
    readingTimeMinutes: 13,
    keywords: ['master manual', 'governance', 'multi-venue', 'staff management', 'system security'],
    screenshots: ['SS-D6-S037', 'SS-D6-S040', 'SS-D6-S044', 'SS-D6-S054'],
    videos: ['SS-D6-V022', 'SS-D6-V023', 'SS-D6-V024', 'SS-D6-V027'],
  },
];

export { HELP_VIDEOS } from './help-videos-manifest';
